CREATE TABLE `fanfiction_settings` (
  `sitekey` varchar(50) NOT NULL DEFAULT '1',
  `sitename` varchar(200) NOT NULL DEFAULT 'Your Site',
  `slogan` varchar(200) NOT NULL DEFAULT 'It''s a cool site!',
  `url` varchar(200) NOT NULL DEFAULT 'http://www.yoursite.com',
  `siteemail` varchar(200) NOT NULL DEFAULT 'you@yoursite.com',
  `tableprefix` varchar(50) NOT NULL DEFAULT '',
  `skin` varchar(50) NOT NULL DEFAULT 'default',
  `hiddenskins` varchar(255) DEFAULT '',
  `language` varchar(10) NOT NULL DEFAULT 'en',
  `submissionsoff` tinyint(1) NOT NULL DEFAULT '0',
  `storiespath` varchar(20) NOT NULL DEFAULT 'stories',
  `store` varchar(5) NOT NULL DEFAULT 'files',
  `autovalidate` tinyint(1) NOT NULL DEFAULT '0',
  `coauthallowed` int NOT NULL DEFAULT '0',
  `maxwords` int NOT NULL DEFAULT '0',
  `minwords` int NOT NULL DEFAULT '0',
  `imageupload` tinyint(1) NOT NULL DEFAULT '0',
 
  `roundrobins` tinyint(1) NOT NULL DEFAULT '0',
 
  `tinyMCE` tinyint(1) NOT NULL DEFAULT '0',
  `allowed_tags` varchar(200) NOT NULL DEFAULT '',
  `favorites` tinyint(1) NOT NULL DEFAULT '0',
  `multiplecats` tinyint(1) NOT NULL DEFAULT '0',
  `newscomments` tinyint(1) NOT NULL DEFAULT '0',
  `logging` tinyint(1) NOT NULL DEFAULT '0',
  `maintenance` tinyint(1) NOT NULL DEFAULT '0',
  `debug` tinyint(1) NOT NULL DEFAULT '0',
  `captcha` tinyint(1) NOT NULL DEFAULT '0',
  `dateformat` varchar(20) NOT NULL DEFAULT 'd/m/y',
  `timeformat` varchar(20) NOT NULL DEFAULT '- h:i a',
  `recentdays` tinyint NOT NULL DEFAULT '7',
  `displaycolumns` tinyint(1) NOT NULL DEFAULT '1',
  `itemsperpage` tinyint NOT NULL DEFAULT '25',
  `extendcats` tinyint(1) NOT NULL DEFAULT '0',
  `displayindex` tinyint(1) NOT NULL DEFAULT '0',
  `defaultsort` tinyint(1) NOT NULL DEFAULT '0',
  `displayprofile` tinyint(1) NOT NULL DEFAULT '0',
  `linkstyle` tinyint(1) NOT NULL DEFAULT '0',
  `linkrange` tinyint NOT NULL DEFAULT '5',
  `reviewsallowed` tinyint(1) NOT NULL DEFAULT '0',
  `ratings` tinyint(1) NOT NULL DEFAULT '0',
  `anonreviews` tinyint(1) NOT NULL DEFAULT '0',
  `revdelete` tinyint(1) NOT NULL DEFAULT '0',
  `rateonly` tinyint(1) NOT NULL DEFAULT '0',
  `pwdsetting` tinyint(1) NOT NULL DEFAULT '0',
  `alertson` tinyint(1) NOT NULL DEFAULT '0',
  `disablepopups` tinyint(1) NOT NULL DEFAULT '0',
  `agestatement` tinyint(1) NOT NULL DEFAULT '0',
  `words` text,
  `version` varchar(10) NOT NULL DEFAULT '3.0',
 
  `anonchallenges` tinyint(1) NOT NULL DEFAULT '0',
  `anonrecs` tinyint(1) NOT NULL DEFAULT '0',
  `rectarget` tinyint(1) NOT NULL DEFAULT '0',
  `autovalrecs` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`sitekey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
